# Generated by Django 5.1.3 on 2024-11-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_user',
        ),
    ]
