# Generated by Django 5.1.3 on 2024-11-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='movein_user',
        ),
    ]
