# Generated by Django 5.1.3 on 2024-11-21 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='Reports_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
