# Generated by Django 5.1.3 on 2024-11-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0003_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
